name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Release-Please
        id: release
        uses: googleapis/release-please-action@v4
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json

      - name: Set up Node
        if: steps.release.outputs.release_created == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        if: steps.release.outputs.release_created == 'true'
        run: npm ci

      - name: Build (Webpack)
        if: steps.release.outputs.release_created == 'true'
        run: npm run build  # webpack --mode production

      - name: Zip extension
        if: steps.release.outputs.release_created == 'true'
        run: zip -r amlathon.zip dist/

      - name: Upload artifact
        if: steps.release.outputs.release_created == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: amlathon-${{ steps.release.outputs.tag_name }}
          path: amlathon.zip